//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
namespace getnet.service.System {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("getnet.service.System.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot define commands if global options or parameters exist..
        /// </summary>
        public static string CannotDefineCommandsIfArgumentsExist {
            get {
                return ResourceManager.GetString("CannotDefineCommandsIfArgumentsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot define multiple parameter lists..
        /// </summary>
        public static string CannotDefineMultipleParameterLists {
            get {
                return ResourceManager.GetString("CannotDefineMultipleParameterLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to value &apos;{0}&apos; isn&apos;t valid for {1}: {2}.
        /// </summary>
        public static string CannotParseValueFmt {
            get {
                return ResourceManager.GetString("CannotParseValueFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Command &apos;{0}&apos; is already defined..
        /// </summary>
        public static string CommandAlreadyDefinedFmt {
            get {
                return ResourceManager.GetString("CommandAlreadyDefinedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name &apos;{0}&apos; cannot be used for a command..
        /// </summary>
        public static string CommandNameIsNotValidFmt {
            get {
                return ResourceManager.GetString("CommandNameIsNotValidFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to error: {0}.
        /// </summary>
        public static string ErrorWithMessageFmt {
            get {
                return ResourceManager.GetString("ErrorWithMessageFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to extra parameter &apos;{0}&apos;.
        /// </summary>
        public static string ExtraParameterFmt {
            get {
                return ResourceManager.GetString("ExtraParameterFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to usage: {0}.
        /// </summary>
        public static string HelpUsageOfApplicationFmt {
            get {
                return ResourceManager.GetString("HelpUsageOfApplicationFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to invalid option {0}.
        /// </summary>
        public static string InvalidOptionFmt {
            get {
                return ResourceManager.GetString("InvalidOptionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to missing command.
        /// </summary>
        public static string MissingCommand {
            get {
                return ResourceManager.GetString("MissingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You must specify a name..
        /// </summary>
        public static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Option &apos;{0}&apos; is already defined..
        /// </summary>
        public static string OptionAlreadyDefinedFmt {
            get {
                return ResourceManager.GetString("OptionAlreadyDefinedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name &apos;{0}&apos; cannot be used for an option..
        /// </summary>
        public static string OptionNameIsNotValidFmt {
            get {
                return ResourceManager.GetString("OptionNameIsNotValidFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to option {0} requires a value.
        /// </summary>
        public static string OptionRequiresValueFmt {
            get {
                return ResourceManager.GetString("OptionRequiresValueFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Options must be defined before any parameters..
        /// </summary>
        public static string OptionsMustBeDefinedBeforeParameters {
            get {
                return ResourceManager.GetString("OptionsMustBeDefinedBeforeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter &apos;{0}&apos; is already defined..
        /// </summary>
        public static string ParameterAlreadyDefinedFmt {
            get {
                return ResourceManager.GetString("ParameterAlreadyDefinedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name &apos;{0}&apos; cannot be used for a parameter..
        /// </summary>
        public static string ParameterNameIsNotValidFmt {
            get {
                return ResourceManager.GetString("ParameterNameIsNotValidFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameters cannot be defined after parameter lists..
        /// </summary>
        public static string ParametersCannotBeDefinedAfterLists {
            get {
                return ResourceManager.GetString("ParametersCannotBeDefinedAfterLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Response file &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        public static string ResponseFileDoesNotExistFmt {
            get {
                return ResourceManager.GetString("ResponseFileDoesNotExistFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to unknown command &apos;{0}&apos;.
        /// </summary>
        public static string UnknownCommandFmt {
            get {
                return ResourceManager.GetString("UnknownCommandFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unmatched quote at position {0}..
        /// </summary>
        public static string UnmatchedQuoteFmt {
            get {
                return ResourceManager.GetString("UnmatchedQuoteFmt", resourceCulture);
            }
        }
    }
}
